### ISSUE TITLE
Synthesizer in deepeval requires an OpenAi key

### ISSUE THREAD

**Issue by alexazarh** [confident-ai/deepeval#1181]
**Describe the bug**
Synthesizer in deepeval 1.5.9 requires an OpenAi key. I'm using a custom LLM (claude via bedrock) so I am not using OpenAi for anything.

**To Reproduce**
aws_bedrock is a custom class that inherits from DeepEvalBaseLLM. It works with with all metrics.
```
from deepeval.synthesizer import Synthesizer
from deepeval.synthesizer.config import StylingConfig, FiltrationConfig
filteration_config = FiltrationConfig(critic_model=aws_bedrock)
synthesizer = Synthesizer(model=aws_bedrock)
```

**Expected behavior**
The deepeval python library should function without a OpenAi key.

**Screenshots**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\deepeval\synthesizer\synthesizer.py", line 94, in __init__
    else FiltrationConfig()
         ^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
    self.critic_model, _ = initialize_model(self.critic_model)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\deepeval\metrics\utils.py", line 266, in initialize_model
    return GPTModel(model=model), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\deepeval\models\gpt_model.py", line 103, in __init__
    super().__init__(model_name)
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\deepeval\models\base_model.py", line 35, in __init__
    self.model = self.load_model(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\deepeval\models\gpt_model.py", line 156, in load_model
    return ChatOpenAI(
           ^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\langchain_core\load\serializable.py", line 111, in __init__
    super().__init__(*args, **kwargs)
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\langchain_openai\chat_models\base.py", line 529, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\git\tyler\Tyler-lacounty-ai\.venv\Lib\site-packages\openai\_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Additional context**
Looks similar to the issue reported here: https://github.com/confident-ai/deepeval/issues/1140

**Comment by penguine-ip** [comment]
Hey @alexazarh ,  I believe the problem is because the FiltrationConfig also requires an LLM: https://docs.confident-ai.com/docs/synthesizer-introduction#filtration-quality

Please provide your LLM instance there are see if it works?

**Comment by alexazarh** [comment]
@penguine-ip thx for your reply.
I'm already passing custom LLM to the FiltrationConfig using the "critic_model" attribute.
Here's the code:
```
filteration_config = FiltrationConfig(critic_model=aws_bedrock)
synthesizer = Synthesizer(model=aws_bedrock)
```

And here is the implementation for the custom LLM:
```
from langchain_aws import ChatBedrock
from deepeval.models.base_model import DeepEvalBaseLLM

class AWSBedrock(DeepEvalBaseLLM):
    def __init__(self, model):
        self.model = model

    def load_model(self):
        return self.model

    def generate(self, prompt: str) -> str:
        chat_model = self.load_model()
        return chat_model.invoke(prompt).content

    async def a_generate(self, prompt: str) -> str:
        chat_model = self.load_model()
        res = await chat_model.ainvoke(prompt)
        return res.content

    def get_model_name(self):
        return "AWS Bedrock Antropic Claude 3.5 Sonnet"


def get_bedrock_model(temperature=0.5):
    return ChatBedrock(model_id="anthropic.claude-3-5-sonnet-20241022-v2:0", model_kwargs={"temperature": temperature})

aws_bedrock = AWSBedrock(model=get_bedrock_model())
```

Any other suggestions?

**Comment by penguine-ip** [comment]
@alexazarh Also you'll need to provide filtration config as well after supplying it with a critic model :)

**Comment by alexazarh** [comment]
Silly error on my end :)
It works now as expected.
Thx!
