### ISSUE TITLE
Version 0.20.5 breaks my Weaviate client

### ISSUE THREAD

**Issue by Vasilije1990** [confident-ai/deepeval#212]
**Describe the bug**
Upgrading to version 0.20.5 breaks my Weaviate client

**To Reproduce**
1. Go to https://github.com/topoteretes/PromethAI-Memory
2. Run the docker and update poetry to 0.20.5
3. Run the RAG tester

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/rag_test_manager.py", line 554, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/rag_test_manager.py", line 511, in main
    result = await start_test("http://public-library.uk/ebooks/59/83.pdf", test_set=test_set, user_id="676", params=None, metadata=metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/rag_test_manager.py", line 319, in start_test
    susu = await memory.dynamic_method_call(memory.semanticmemory_class, 'fetch_memories',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/vectorstore_manager.py", line 283, in dynamic_method_call
    return await method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/vectordb/basevectordb.py", line 236, in fetch_memories
    return await self.vector_db.fetch_memories(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI-Memory/level_3/vectordb/vectordb.py", line 199, in fetch_memories
    .do()
     ^^^^
  File "/Users/vasa/Projects/PromethAI/venv/lib/python3.11/site-packages/weaviate/gql/get.py", line 1342, in do
    return super().do()
           ^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI/venv/lib/python3.11/site-packages/weaviate/gql/filter.py", line 80, in do
    return response.json()  # success
           ^^^^^^^^^^^^^^^
  File "/Users/vasa/Projects/PromethAI/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sentry is attempting to send 3 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit`

**Comment by penguine-ip** [comment]
Hey @Vasilije1990, can you please specify which RAG tester you're using?

**Comment by Vasilije1990** [comment]
@penguine-ip one I built myself. It's in the repo provided

**Comment by Vasilije1990** [comment]
Resolved, closing
