### ISSUE TITLE
Type Hinting issue with python<=3.8

### ISSUE THREAD

**Issue by navkar98** [confident-ai/deepeval#594]
**Describe the bug**
Built-in collection types such as list and dict don't work with python<=3.8 for Type Hinting Generics. 

**To Reproduce**
1. Create a virtual environment with python <= 3.8
2. Try to log in using `deepeval login`
3. You'll see an error: `TypeError: 'type' object is not subscriptable`

**Expected behavior**
Typing should work with python<=3.8.

**Error Traceback**
```
Traceback (most recent call last):
   File "/venv/bin/deepeval", line 5, in <module>
     from deepeval.cli.main import app
   File "/venv/lib/python3.8/site-packages/deepeval/\_\_init__.py", line 8, in <module>
     from deepeval.evaluate import evaluate, assert_test
   File "/venv/lib/python3.8/site-packages/deepeval/evaluate.py", line 15, in <module>
     from deepeval.test_run import test_run_manager, APITestCase, MetricsMetadata
   File "/venv/lib/python3.8/site-packages/deepeval/test_run/\_\_init__.py", line 1, in <module>
     from .test_run import (
   File "/venv/lib/python3.8/site-packages/deepeval/test_run/test_run.py", line 65, in <module>
     class TestRun(BaseModel):
   File "/venv/lib/python3.8/site-packages/deepeval/test_run/test_run.py", line 81, in TestRun
     hyperparameters: Optional[dict[Any, Any]] = Field(None)
TypeError: 'type' object is not subscriptable
```

**Comment by penguine-ip** [comment]
@navkar98 thanks so much, looking forward to it!

**Comment by navkar98** [comment]
@penguine-ip I created a PR but it failed as I didn't had api key to pass. Can you let me know what can I do about it?

**Comment by penguine-ip** [comment]
@navkar98 no problem, everything else is working so i just merged it, thanks a lot! New release out in 1-2 hours.
